baseURL = "https://rob.stumb.org"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Rob Stumborg"
theme = "robstumborg-v2"
summaryLength = 10

[params]
  lookingForWork = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'xcode'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
    post = "/notes/:slug"

[[menu.main]]
name = "my work"
url = "/work"
weight = 1

[[menu.main]]
name = "notes"
url = "/notes"
weight = 2

[[menu.main]]
name = "repos"
url = "/repos"
weight = 3
